image:
  repository: ghcr.io/OWNER/secure-app   # se sobreescribe en el pipeline
  tag: "latest"                          # se sobreescribe en el pipeline
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ "ALL" ]

livenessProbe:
  path: /health
  port: 3000
readinessProbe:
  path: /health
  port: 3000

# namespace se pasa por CLI
