apiVersion: apps/v1
kind: Deployment
metadata:
  name: signed-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels: { app: signed-app }
  template:
    metadata:
      labels: { app: signed-app }
    spec:
      containers:
        - name: app
          image: ghcr.io/<OWNER>/signed-app:v1   # <--- debe estar FIRMADA
          ports: [{ containerPort: 3000 }]
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
  name: signed-app
  namespace: apps
spec:
  type: ClusterIP
  selector: { app: signed-app }
  ports:
    - port: 80
      targetPort: 3000
