apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-api-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: demo-api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
    target:
      kind: Deployment
      name: demo-api

images:
  - name: REGISTRY/demo-api
    newName: myacr.azurecr.io/demo-api
    newTag:  sha-latest     # reemplazado por CI/CD
