name: Terraform Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terrascan (AWS + Azure) -> SARIF
        uses: tenable/terrascan-action@v1.5.0
        with:
          iac_type: terraform
          policy_type: aws,azure
          only_warn: false          # true si no quieres fallar el job
          sarif_upload: true        # publica resultados en Code Scanning
          iac_version: v14          # o v12/v13 según tu TF
          path: .                   # raíz del repo
