name: Terraform Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install terrascan
        run: |
          curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_Linux_x86_64.tar.gz -o terrascan.tar.gz
          tar -xvzf terrascan.tar.gz terrascan && sudo mv terrascan /usr/local/bin

      - name: Terrascan AWS + Azure
        run: terrascan scan -t aws -t azure
